apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ include "frontend-service.name" . }}
